language: php

php:
  - 5.5
  - 5.6

env:
  matrix:
    - TYPO3_VERSION=7.6.*

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - export typo3DatabaseName="typo3";
  - export typo3DatabaseHost="localhost";
  - export typo3DatabaseUsername="root";
  - export typo3DatabasePassword="";

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running functional tests";
    find 'Tests/Functional' -wholename '*Test.php' | xargs -I {} .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}
